print("Downloading files...")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Zimv/main.lua main.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Zimv/movement.lua movement.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Zimv/inventory.lua inventory.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Zimv/planner.lua planner.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Zimv/scanner.lua scanner.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Zimv/fuel.lua fuel.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Zimv/state.lua state.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Zimv/config.lua config.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Zimv/digger.lua digger.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Zimv/logger.lua logger.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Zimv/logger.lua startup")
print("Download complete! Rebooting in 3 seconds...")
sleep(3)
os.reboot()
