print("Downloading files...")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Shigger/refs/heads/main/Shigger/main.lua main.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Shigger/refs/heads/main/Shigger/movement.lua movement.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Shigger/refs/heads/main/Shigger/inventory.lua inventory.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Shigger/refs/heads/main/Shigger/planner.lua planner.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Shigger/refs/heads/main/Shigger/scanner.lua scanner.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Shigger/refs/heads/main/Shigger/fuel.lua fuel.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Shigger/refs/heads/main/Shigger/state.lua state.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Shigger/refs/heads/main/Shigger/config.lua config.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Shigger/refs/heads/main/Shigger/digger.lua digger.lua")
print("Download complete! Now run the main file to start.")

