print("Downloading files...")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Shigger/main.lua main.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Shigger/movement.lua movement.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Shigger/inventory.lua inventory.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Shigger/planner.lua planner.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Shigger/scanner.lua scanner.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Shigger/fuel.lua fuel.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Shigger/state.lua state.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Shigger/config.lua config.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Shigger/digger.lua digger.lua")
shell.run("wget https://raw.githubusercontent.com/Irecco1/Zimv/refs/heads/main/Shigger/logger.lua logger.lua")
print("Download complete! Rebooting in 3 seconds...")
sleep(3)
os.reboot()
